### PR TITLE
feat: Allow multiple selections in Select component

### PR DESCRIPTION
**Pull request by dogmar**
Needed for https://linear.app/pluralsh/issue/ENG-1126/add-filter-to-component-list

### CODE REVIEW

**Review by maciaszczykm — APPROVED** [review]
Looks great!

**Review by floreks — APPROVED** [review]

**Comment by floreks** [comment]
Awesome! QQ: Is there an option to mark select as disabled? I have only found `isDisabled` property but it does not change the UI, only blocks the input.

**Review by dherault — APPROVED** [review]

**Comment by dogmar** [comment]
> Awesome! QQ: Is there an option to mark select as disabled? I have only found `isDisabled` property but it does not change the UI, only blocks the input.

I'll make a new ticket to add that functionality. How urgently do you need it, @floreks ?

**Comment by floreks** [comment]
No rush. I have ended up using disabled input. Looks almost the same :) Might be useful in the future though.

**Pull request merged**
