### PR TITLE
fix(build): Reconfigure vite as per official migration guide and fix firebase deploy

### PR DESCRIPTION
**Pull request by floreks**
Also updated eslint config to properly recognize and fix config files, not only src dir.

Tested with:
1. `yarn start`
2. `yarn storybook:serve-static`
3. `yarn build` and `yarn add @pluralsh/design-system@file:../../design-system` in the plural app. Then `yarn start` to make sure that it works as a dependency in the app.
4. `yarn firebase:start` <- emulates firebase static serve

### CODE REVIEW

**Comment by floreks** [comment]
Preview finally works! :tada:

**Comment by DavidSpek** [comment]
Was preview broken again? I had fixed this previously, although it could use some cleanup.

**Comment by floreks** [comment]
Unfortunately, the preview and importing design system as a library in other apps were broken. We should also revisit renovate the auto-merge feature since we do not have real control over the release process now. This is very important now since the storybook was updated to the v7 alpha. It is very unstable and any patch update can break everything again.

**Comment by DavidSpek** [comment]
Preferably we’d create tests rather than disable auto-merging, since otherwise dependencies will never get updated. However, if storybook specifically is unstable we can disable auto-merging for just storybook.

**Comment by floreks** [comment]
For example, the issue that we've hit with firebase and the preview system would not be easily testable. It was really hard to pin down and debug. Every manual and local test was working perfectly fine. Another thing is that even though the prod build was passing, the library could not be imported by other apps (plural, console) as they were failing to start.

Since this is a dependency and it is released after every PR merge, it can be really dangerous to keep automerge enabled.

**Comment by DavidSpek** [comment]
If the Plural and console CI fails when it tries to update the design system to the new version that is good. I’d consider that catching the problem. We can also change the release to only happen when non-bots push to main. But that might make pinpointing the version that doesn’t have the issue and rolling back more difficult or invasive.

Disabling auto-merging is a possibility, but there needs to be a plan and workflow in place that ensures we keep dependencies up to date. We can have renovate group together all updates (with a high likelihood the PR needs manual fixes) or only run weekly. But if there’s no way for us to check an update is valid locally I’m not sure how disabling auto-merging would help. If the solution is to check the preview and see that what we’re expecting to be there is there, we could also run that in a cypress test.

After over a year where dependencies have rarely been updated, even with Renovate creating PRs, I think auto-merging is the best solution to avoid going back to this. The main thing we want to avoid is user facing issues, which should be filtered out if the Plural and console CI jobs fail for a broken design system version. However, disabling auto-merging for certain packages is definitely a valid option as well. But we should default to auto-merge as much as possible.

**Comment by floreks** [comment]
> If the Plural and console CI fails when it tries to update the design system to the new version that is good. I’d consider that catching the problem. We can also change the release to only happen when non-bots push to main. But that might make pinpointing the version that doesn’t have the issue and rolling back more difficult or invasive.

This is definitely far from ideal since it effectively favors releasing a broken library and catching the error once another application tries to use it. We should be focusing on trying to identify issues as soon as possible, ideally before the release.

> Disabling auto-merging is a possibility, but there needs to be a plan and workflow in place that ensures we keep dependencies up to date. We can have renovate group together all updates (with a high likelihood the PR needs manual fixes) or only run weekly. But if there’s no way for us to check an update is valid locally I’m not sure how disabling auto-merging would help. If the solution is to check the preview and see that what we’re expecting to be there is there, we could also run that in a cypress test.
>
> After over a year where dependencies have rarely been updated, even with Renovate creating PRs, I think auto-merging is the best solution to avoid going back to this. The main thing we want to avoid is user facing issues, which should be filtered out if the Plural and console CI jobs fail for a broken design system version. However, disabling auto-merging for certain packages is definitely a valid option as well. But we should default to auto-merge as much as possible.

I wouldn't consider using an older version of dependency a disadvantage in any way unless there is a security issue that the newer version fixes. Using stable versions of known dependencies is usually the best since it allows us to keep a stable working environment. This is also why we have updated our `package.json` to use only exact version matching. Right now renovate configuration kind of counters it and works the same as if we would update `package.json` dependencies to use non-exact version matching.

For now, I'd definitely disable auto-merge for the alpha version of all storybook deps since the creators themselves said that every patch version can introduce breaking changes. I'd probably also stick only to automated patch version updates. It is less likely that a patch update will break compatibility.

**Review by maciaszczykm — APPROVED** [review]
Great!

**Comment by maciaszczykm** [comment]
I agree that having tests that will cover all dependency updates is nearly impossible and that's why adding more restrictive rules when it comes to merging is needed. Especially when it comes to updating to alpha versions or major ones. This should always be tested by us.

**Pull request merged**
