### PR TITLE
Add Tag

### PR DESCRIPTION
**Pull request by dherault**

### CODE REVIEW

**Comment by michaeljguarino** [comment]
Is the radius of the tag according to the design system?  We should talk to Aliza about reducing that as the default, I think it looks better a bit more squared usually.

**Comment by dherault** [comment]
It is according to the DS, in general I take little to no liberties in the implementation compared with the DS.

**Comment by dherault** [comment]
I'm asking Aliza

**Comment by dherault** [comment]
Sorry it needed some fixes...

**Pull request merged**
