### PR TITLE
Implement new RepositoryCard

### PR DESCRIPTION
**Pull request by dherault**
Specs:
image

Delivered:
image

As you can see there are two main differences:
- The chip component has a border. Chris told me this would be the way to go.
- The "+5" does not display and instead the chips wrap. @dogmar do you agree this would require a `useRef` on every chip component with multiple calls to `getBoundingClientRect` on both the chips and their container and a bit of script to make the computations right? So I've decided to wait until we find a repository with more than 4 chips because that seemed like an overkill feature for our needs. I'll explain my choices to Chris and Nick.

Notable change:
There are no more multiple sizes for the component.

### CODE REVIEW

**Comment by dogmar** [comment]
> Notable change:
> There are no more multiple sizes for the component.

I see 3 different variants in the [Design System Figma file](https://www.figma.com/file/i3IQooR2YCCXiCJNL98lWr/%F0%9F%8E%A8-Official-Design-System?node-id=2232%3A28199). Is there a new version without multiple sizes now?

> The "+5" does not display and instead the chips wrap. @dogmar do you agree this would require a useRef on every chip component with multiple calls to getBoundingClientRect on both the chips and their container and a bit of script to make the computations right? So I've decided to wait until we find a repository with more than 4 chips because that seemed like an overkill feature for our needs. I'll explain my choices to Chris and Nick.

Yes, you'd probably need a ResizeObserver as well. There's a new component I made for `Select` boxes called `ListBoxItemChipList` that we should extend to be more generic for this case eventually. Right now, you can just limit the total number of chips listed, but it doesn't do any checking to make sure they all stay on one line.

**Comment by floreks** [comment]
I think @dogmar is right about the design. The provided link points to the most recent design that I know of, which uses an app icon component and supports different card sizes.

**Comment by dherault** [comment]
Sorry I referred to an old link. I'm on it.

**Comment by dherault** [comment]
There you go, more screen responsiveness.

**Comment by dogmar** [comment]
Is there a way to choose the variants without relying on a media query? So we can achieve [this layout](https://www.figma.com/file/kZ69OGXTQe3Gu0wzGdDyoO/Marketplace-Tab) with multiple sizes on one page?

**Comment by dherault** [comment]
Let me fix that

**Review by dogmar — APPROVED** [review]

**Pull request merged**
